# -*- coding: utf-8 -*-
"""生成诺丁汉 / 北京 实时天气卡片（纯 Pillow 绘制，含手绘天气图标）"""
from PIL import Image, ImageDraw, ImageFont
import datetime

W, H = 920, 520
FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
FONT_B = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"

f_title = ImageFont.truetype(FONT_B, 40)
f_sub = ImageFont.truetype(FONT, 20)
f_city = ImageFont.truetype(FONT_B, 34)
f_temp = ImageFont.truetype(FONT_B, 96)
f_cond = ImageFont.truetype(FONT, 26)
f_note = ImageFont.truetype(FONT, 18)

# ---------- 背景竖向渐变 ----------
bg = Image.new("RGB", (W, H))
d = ImageDraw.Draw(bg)
top, bot = (34, 48, 82), (14, 20, 36)
for y in range(H):
    t = y / (H - 1)
    d.line([(0, y), (W, y)], fill=(
        int(top[0] + (bot[0] - top[0]) * t),
        int(top[1] + (bot[1] - top[1]) * t),
        int(top[2] + (bot[2] - top[2]) * t)))

img = bg.convert("RGBA")
d = ImageDraw.Draw(img)

# ---------- 顶部标题 ----------
d.text((44, 34), "Weather Report", font=f_title, fill=(240, 245, 255))
d.text((46, 84), "Nottingham  ·  Beijing        source: wttr.in (realtime)",
       font=f_sub, fill=(150, 170, 205))

d.line([(44, 116), (W - 44, 116)], fill=(90, 115, 160), width=2)


def draw_sun(cx, cy, r):
    d.ellipse([cx - r, cy - r, cx + r, cy + r], fill=(255, 205, 70))
    import math
    for i in range(12):
        a = math.radians(i * 30)
        x1, y1 = cx + math.cos(a) * (r + 8), cy + math.sin(a) * (r + 8)
        x2, y2 = cx + math.cos(a) * (r + 20), cy + math.sin(a) * (r + 20)
        d.line([(x1, y1), (x2, y2)], fill=(255, 205, 70), width=4)


def draw_cloud(cx, cy, s=1.0, color=(232, 238, 248), dark=False):
    c = (170, 182, 202) if dark else color
    d.ellipse([cx - 60 * s, cy - 26 * s, cx - 4 * s, cy + 28 * s], fill=c)
    d.ellipse([cx - 34 * s, cy - 50 * s, cx + 26 * s, cy + 24 * s], fill=c)
    d.ellipse([cx - 6 * s, cy - 30 * s, cx + 60 * s, cy + 28 * s], fill=c)
    d.rectangle([cx - 60 * s, cy + 2 * s, cx + 60 * s, cy + 28 * s], fill=c)


def draw_rain(cx, cy, s=1.0):
    for i, dx in enumerate((-40, -12, 16, 44)):
        x = cx + dx * s
        y = cy + 34 * s + (8 if i % 2 else 0)
        d.line([(x, y), (x - 7 * s, y + 30 * s)], fill=(110, 190, 255), width=5)
        d.ellipse([x - 9 * s, y + 28 * s, x + 1 * s, y + 38 * s], fill=(110, 190, 255))


# ---------- 两张卡片 ----------
cards = [
    dict(x=44, city="Nottingham", temp="+10",
         cond="Cloudy", icon="cloud", accent=(120, 190, 255)),
    dict(x=480, city="Beijing", temp="+20",
         cond="Light Rain", icon="rain", accent=(255, 190, 90)),
]

for c in cards:
    x = c["x"]
    y0, y1 = 146, 452
    d.rounded_rectangle([x, y0, x + 396, y1], radius=26,
                        fill=(40, 55, 88, 235), outline=c["accent"], width=2)
    # 城市名
    d.text((x + 28, y0 + 26), c["city"], font=f_city, fill=(240, 245, 255))
    # 温度
    d.text((x + 24, y0 + 82), c["temp"], font=f_temp, fill=c["accent"])
    tw = d.textlength(c["temp"], font=f_temp)
    d.text((x + 30 + tw, y0 + 128), "C", font=f_cond, fill=(190, 205, 230))
    # 天气图标
    icx, icy = x + 300, y0 + 200
    if c["icon"] == "cloud":
        draw_sun(icx + 26, icy - 26, 26)
        draw_cloud(icx - 8, icy + 10, 1.0)
    else:
        draw_cloud(icx, icy - 10, 1.0, dark=True)
        draw_rain(icx, icy - 4)
    # 状况文字
    d.text((x + 28, y1 - 58), c["cond"], font=f_cond, fill=(215, 226, 245))

# ---------- 底部说明 ----------
ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
d.text((44, H - 44), "generated by jzk server bot   ·   " + ts,
       font=f_note, fill=(120, 140, 175))

img.convert("RGB").save("weather_card.png", "PNG")
print("saved weather_card.png", img.size)
